# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: file_processor.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x66ile_processor.proto\x12\rfileprocessor\"S\n\x11\x46ileUploadRequest\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0e\n\x06\x66ileId\x18\x02 \x01(\t\x12\x10\n\x08\x66ilename\x18\x03 \x01(\t\x12\x0c\n\x04\x66ile\x18\x04 \x01(\x0c\"R\n\x0c\x46ileMetadata\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tpageCount\x18\x02 \x01(\x03\x12\x10\n\x08\x66ilesize\x18\x03 \x01(\x03\x12\x0e\n\x06locale\x18\x04 \x01(\t\"x\n\x13\x46ileProcessResponse\x12\x0e\n\x06\x66ileId\x18\x01 \x01(\t\x12-\n\x08metadata\x18\x02 \x01(\x0b\x32\x1b.fileprocessor.FileMetadata\x12\"\n\x05pages\x18\x03 \x03(\x0b\x32\x13.fileprocessor.Page\"\'\n\x04Page\x12\x0e\n\x06pageId\x18\x01 \x01(\x03\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t2d\n\rFileProcessor\x12S\n\x0bProcessFile\x12 .fileprocessor.FileUploadRequest\x1a\".fileprocessor.FileProcessResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_processor_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_FILEUPLOADREQUEST']._serialized_start=39
  _globals['_FILEUPLOADREQUEST']._serialized_end=122
  _globals['_FILEMETADATA']._serialized_start=124
  _globals['_FILEMETADATA']._serialized_end=206
  _globals['_FILEPROCESSRESPONSE']._serialized_start=208
  _globals['_FILEPROCESSRESPONSE']._serialized_end=328
  _globals['_PAGE']._serialized_start=330
  _globals['_PAGE']._serialized_end=369
  _globals['_FILEPROCESSOR']._serialized_start=371
  _globals['_FILEPROCESSOR']._serialized_end=471
# @@protoc_insertion_point(module_scope)
