// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: subscriptions.proto

#include "subscriptions.pb.h"
#include "subscriptions.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace subscription_pb {

static const char* Subscription_method_names[] = {
  "/subscription_pb.Subscription/CheckHealth",
};

std::unique_ptr< Subscription::Stub> Subscription::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Subscription::Stub> stub(new Subscription::Stub(channel, options));
  return stub;
}

Subscription::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CheckHealth_(Subscription_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Subscription::Stub::CheckHealth(::grpc::ClientContext* context, const ::subscription_pb::HealthCheckRequest& request, ::subscription_pb::HealthCheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::subscription_pb::HealthCheckRequest, ::subscription_pb::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CheckHealth_, context, request, response);
}

void Subscription::Stub::async::CheckHealth(::grpc::ClientContext* context, const ::subscription_pb::HealthCheckRequest* request, ::subscription_pb::HealthCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::subscription_pb::HealthCheckRequest, ::subscription_pb::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckHealth_, context, request, response, std::move(f));
}

void Subscription::Stub::async::CheckHealth(::grpc::ClientContext* context, const ::subscription_pb::HealthCheckRequest* request, ::subscription_pb::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CheckHealth_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::subscription_pb::HealthCheckResponse>* Subscription::Stub::PrepareAsyncCheckHealthRaw(::grpc::ClientContext* context, const ::subscription_pb::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::subscription_pb::HealthCheckResponse, ::subscription_pb::HealthCheckRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CheckHealth_, context, request);
}

::grpc::ClientAsyncResponseReader< ::subscription_pb::HealthCheckResponse>* Subscription::Stub::AsyncCheckHealthRaw(::grpc::ClientContext* context, const ::subscription_pb::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCheckHealthRaw(context, request, cq);
  result->StartCall();
  return result;
}

Subscription::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Subscription_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Subscription::Service, ::subscription_pb::HealthCheckRequest, ::subscription_pb::HealthCheckResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Subscription::Service* service,
             ::grpc::ServerContext* ctx,
             const ::subscription_pb::HealthCheckRequest* req,
             ::subscription_pb::HealthCheckResponse* resp) {
               return service->CheckHealth(ctx, req, resp);
             }, this)));
}

Subscription::Service::~Service() {
}

::grpc::Status Subscription::Service::CheckHealth(::grpc::ServerContext* context, const ::subscription_pb::HealthCheckRequest* request, ::subscription_pb::HealthCheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace subscription_pb

