apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriptions
  namespace: eduhelper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: subscriptions
  template:
    metadata:
      labels:
        app: subscriptions
    spec:
      containers:
      - name: subscriptions
        image: 397789365835.dkr.ecr.ap-southeast-1.amazonaws.com/esd-eduhelper-eks-ecr-production:subscriptions
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        env:
          - name: GRPC_SERVER_ADDRESS
            value: "0.0.0.0:50051"
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                key: DB_NAME
                name: eks-secrets
          - name: DB_HOSTADDR
            valueFrom:
              secretKeyRef:
                key: DB_HOST
                name: eks-secrets
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: DB_USERNAME
                name: eks-secrets
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DB_PASSWORD
                name: eks-secrets
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always
status: {}