apiVersion: v1
kind: Service
metadata:
  name: proxy-app
  namespace: itsag2t2
spec:
  selector:
    app: proxy-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
status:
  loadBalancer: {}