apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-app
  namespace: itsag2t2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: proxy-app
  template:
    metadata:
      labels:
        app: proxy-app
    spec:
      containers:
      - name: proxy-app
        image: 163683790602.dkr.ecr.ap-southeast-1.amazonaws.com/itsag2t2-eks-ecr-production:proxy-app
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
          - name: ENVIRONMENT
            value: production
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: JWT_SECRET_KEY
                name: eks-secrets
          - name: HTTPS_ALLOWED_ORIGINS
            value: "https://itsag2t2.com"
          - name: HTTP_SERVER_ADDRESS
            value: ":8080"
          - name: GRPC_USER_STORAGE_SERVICE_ADDRESS
            value: "user-storage:50051"
          - name: GRPC_USER_AUTH_SERVICE_ADDRESS
            value: "user-auth:50052"
          - name: GRPC_PERMISSIONS_SERVICE_ADDRESS
            value: "permissions:50053"
          - name: GRPC_POINTS_LEDGER_SERVICE_ADDRESS
            value: "points-ledger:50054"
          - name: GRPC_MAKERCHECKER_SERVICE_ADDRESS
            value: "makerchecker:50055"
          - name: ELASTICSEARCH_URL
            valueFrom:
              secretKeyRef:
                key: ELASTICSEARCH_URL
                name: eks-secrets
          - name: ELASTICSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                key: ELASTICSEARCH_USERNAME
                name: eks-secrets
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                key: ELASTICSEARCH_PASSWORD
                name: eks-secrets
          - name: OPENSEARCH_URL
            valueFrom:
              secretKeyRef:
                key: OPENSEARCH_URL
                name: eks-secrets
          - name: OPENSEARCH_REGION
            valueFrom:
              secretKeyRef:
                key: OPENSEARCH_REGION
                name: eks-secrets
          - name: OPENSEARCH_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                key: OPENSEARCH_ACCESS_KEY_ID
                name: eks-secrets
          - name: OPENSEARCH_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                key: OPENSEARCH_SECRET_ACCESS_KEY
                name: eks-secrets
          - name: KAFKA_BROKERS
            valueFrom:
              secretKeyRef:
                key: KAFKA_BROKERS
                name: eks-secrets
        livenessProbe:
          httpGet:
            path: /api/v1/healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/v1/healthz
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
      restartPolicy: Always
status: {}