apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging
  namespace: itsag2t2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logging
  template:
    metadata:
      labels:
        app: logging
    spec:
      containers:
      - name: logging
        image: 163683790602.dkr.ecr.ap-southeast-1.amazonaws.com/itsag2t2-eks-ecr-production:logging
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        env:
          - name: ENVIRONMENT
            value: production
          - name: ELASTICSEARCH_URL
            valueFrom:
              secretKeyRef:
                key: ELASTICSEARCH_URL
                name: eks-secrets
          - name: ELASTICSEARCH_USERNAME
            valueFrom:
              secretKeyRef:
                key: ELASTICSEARCH_USERNAME
                name: eks-secrets
          - name: ELASTICSEARCH_PASSWORD
            valueFrom:
              secretKeyRef:
                key: ELASTICSEARCH_PASSWORD
                name: eks-secrets
          - name: KAFKA_BROKERS
            valueFrom:
              secretKeyRef:
                key: KAFKA_BROKERS
                name: eks-secrets
          - name: HTTP_SERVER_ADDR
            value: ":8082"  
        livenessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always
status: {}