apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: makerchecker
  namespace: itsag2t2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: makerchecker
  minReplicas: 1
  maxReplicas: 6
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75