apiVersion: apps/v1
kind: Deployment
metadata:
  name: make-payment
  namespace: eduhelper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: make-payment
  template:
    metadata:
      labels:
        app: make-payment
    spec:
      containers:
      - name: make-payment
        image: 397789365835.dkr.ecr.ap-southeast-1.amazonaws.com/esd-eduhelper-eks-ecr-production:make-payment
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        env:
          - name: GRPC_SERVER_ADDRESS
            value: "0.0.0.0:50051"
          - name: SUBSCRIPTION_SERVICE_HOST
            value: "subscriptions"
          - name: SUBSCRIPTION_SERVICE_PORT
            value: "50051"
          - name: PAYMENT_SERVICE_HOST
            value: "payment"
          - name: PAYMENT_SERVICE_PORT
            value: "50051"
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always
status: {}