apiVersion: apps/v1
kind: Deployment
metadata:
  name: save-notes
  namespace: eduhelper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: save-notes
  template:
    metadata:
      labels:
        app: save-notes
    spec:
      containers:
      - name: save-notes
        image: 397789365835.dkr.ecr.ap-southeast-1.amazonaws.com/esd-eduhelper-eks-ecr-production:save-notes
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        env:
          - name: CONTENT_SERVICE_ADDRESS
            value: "contents:50051"
          - name: RABBITMQ_SERVER
            valueFrom:
              secretKeyRef:
                key: RABBITMQ_HOST
                name: eks-secrets
          - name: RABBITMQ_USERNAME
            valueFrom:
              secretKeyRef:
                key: RABBITMQ_USERNAME
                name: eks-secrets
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                key: RABBITMQ_PASSWORD
                name: eks-secrets
          - name: OPENAI_API_KEYS
            valueFrom:
              secretKeyRef:
                key: OPENAI_API_KEYS
                name: eks-secrets
      restartPolicy: Always
status: {}