version: "3.8"

secrets:
  kong_db_password:
    file: ./kong_db_password.txt
  ngrok_config:
    file: ../../backend/ngrok/ngrok.yml

x-common-env:
  &common-env
  KONG_PG_HOST: kong-database
  KONG_PG_USER: kong
  KONG_PG_PASSWORD_FILE: /run/secrets/kong_db_password

networks:
  default:

volumes:
  kong-data: {}
  postgres-db-volume: {}
  # user-storage-db-volume: {}
  # notes-db-volume: {}
  # subscriptions-db-volume: {}
  contents-db-volume: {}

services:
  # Required for Stripe webhook
  ngrok:
    image: ngrok/ngrok:alpine
    secrets:
      - ngrok_config
    command:
      - start
      - --all
      - --config
      - /run/secrets/ngrok_config

  kong-gateway:
    image: kong-gateway:1.0
    build: ../../backend/kong-gateway
    environment:
      <<: *common-env
      KONG_DATABASE: off
      KONG_PLUGINS: bundled,authn-kong,rawstring-adapter
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml 
    ports:
      - "8000:8000" # Proxy
      # - "8001:8001" # Admin API
      - "8443:8443" # Proxy SSL
      - "8444:8444" # Admin API SSL # hide
    depends_on:
      user-storage-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 5
    secrets:
      - kong_db_password
    restart: on-failure
    volumes:
      - ../../backend/kong-gateway/kong.yml:/etc/kong/kong.yml 
      - ../../backend/kong-gateway/authn-kong:/usr/local/share/lua/5.1/kong/plugins/authn-kong 
      - ../../backend/kong-gateway/rawstring-adapter:/usr/local/share/lua/5.1/kong/plugins/rawstring-adapter 
      - ../../backend/kong-gateway/protos:/usr/local/share/lua/5.1/kong/protos

  postgres-db:
    image: postgres:alpine3.18
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
      - ../sql_table/create_user_storage_table.sql:/docker-entrypoint-initdb.d/user_storage.sql
      - ../sql_table/create_subscriptions_table.sql:/docker-entrypoint-initdb.d/subscriptions.sql
      - ../sql_table/create_notes_table.sql:/docker-entrypoint-initdb.d/create_notes_table.sql
    environment:
      POSTGRES_DB: esd-db
      POSTGRES_USER: esd-user
      POSTGRES_PASSWORD: esd-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U esd-user -d esd-db"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-redis:
    image: redis:7.2-rc2-alpine3.18
    command: redis-server --requirepass password
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "password", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    
  handle-temporary-contents-service:
    build: ../../backend/complex/handle-temporary-contents
    image: handle-temporary-contents-service:1.0
    env_file:
      - ../../backend/complex/handle-temporary-contents/.env
    depends_on:
      payment-service:
        condition: service_healthy
      subscription-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  make-payment-service:
    build: ../../backend/complex/make-payment
    image: make-payment-service:1.0
    env_file:
      - ../../backend/complex/make-payment/.env
    depends_on:
      payment-service:
        condition: service_healthy
      subscription-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  subscription-service:
    build: ../../backend/simple/subscriptions
    image: subscription-service:1.0
    env_file:
      - ../../backend/simple/subscriptions/.env
    depends_on:
      postgres-db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  notes-service:
    build: ../../backend/simple/notes
    env_file:
      - ../../backend/simple/notes/.env
    depends_on:
      postgres-db:
        condition: service_healthy

  user-storage-service:
    build: ../../backend/simple/user-storage
    image: user-storage-service:1.0
    env_file:
      - ../../backend/simple/user-storage/.env
    depends_on:
      postgres-db:
        condition: service_healthy
      user-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  payment-service:
    build: ../../backend/simple/payment
    image: payment-service:1.0
    env_file:
      - ../../backend/simple/payment/.env
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  contents-db:
    image: bitnami/cassandra:4.1.4
    volumes:
      - contents-db-volume:/bitnami
      - ../sql_table/create_contents_table.cql:/docker-entrypoint-initdb.d/create_contents_table.cql
    healthcheck:
      # TODO: Not secure. Username and password are exposed in the command.
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra"]
      interval: 30s
      timeout: 10s
      retries: 3

  contents-redis:
    image: redis:7.2-rc2-alpine3.18
    command: redis-server --requirepass password
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "password", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  view-notes-service:
    build: ../../backend/complex/view-notes
    image: view-notes-service:1.0
    env_file:
      - ../../backend/complex/view-notes/.env
    depends_on:
      notes-service:
        # TODO: Set up healthcheck for notes service
        condition: service_started
      contents-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    
  contents-service:
    build: ../../backend/simple/contents
    image: content-service:1.0
    env_file:
      - ../../backend/simple/contents/.env
    depends_on:
      contents-db:
        condition: service_healthy
      contents-redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=:50051"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  frontend-client:
    build: ../../client
    image: client:1.0
    depends_on:
      kong-gateway:
        condition: service_healthy
    ports:
      - "3001:3001"

  upload-notes:
    build: ../../backend/complex/upload-notes
    image: upload-notes:1.0
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "user"
      RABBITMQ_DEFAULT_PASS: "password"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  pdf-reader:
    build:
      context: ../../backend/simple/fileprocessor
    # logging:
    #   driver: fluentd
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: docker.container.pdf-reader
      
  
  process-chunks:
    build:
      context: ../../backend/complex/process-chunks
    env_file:
      - ../../backend/complex/process-chunks/.env
    depends_on:
      rabbitmq:
        condition: service_healthy
