apiVersion: v1
kind: Service
metadata:
  name: handle-temporary-contents
  namespace: eduhelper
spec:
  selector:
    app: handle-temporary-contents
  ports:
  - protocol: TCP
    port: 50051  
    targetPort: 50051