# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payment.proto

require 'google/protobuf'


descriptor_data = "\n\rpayment.proto\x12\x07payment\"\'\n\x0f\x43heckoutRequest\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail\"$\n\x10\x43heckoutResponse\x12\x10\n\x03url\x18\x01 \x01(\tR\x03url\"\"\n\x0eWebhookRequest\x12\x10\n\x03raw\x18\x01 \x01(\tR\x03raw\"\'\n\x0fWebhookResponse\x12\x14\n\x05\x65mail\x18\x01 \x01(\tR\x05\x65mail2\x8e\x01\n\rStripeService\x12?\n\x08\x43heckout\x12\x18.payment.CheckoutRequest\x1a\x19.payment.CheckoutResponse\x12<\n\x07Webhook\x12\x17.payment.WebhookRequest\x1a\x18.payment.WebhookResponseBW\n\x0b\x63om.paymentB\x0cPaymentProtoP\x01\xa2\x02\x03PXX\xaa\x02\x07Payment\xca\x02\x07Payment\xe2\x02\x13Payment\\GPBMetadata\xea\x02\x07Paymentb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool

begin
  pool.add_serialized_file(descriptor_data)
rescue TypeError
  # Compatibility code: will be removed in the next major version.
  require 'google/protobuf/descriptor_pb'
  parsed = Google::Protobuf::FileDescriptorProto.decode(descriptor_data)
  parsed.clear_dependency
  serialized = parsed.class.encode(parsed)
  file = pool.add_serialized_file(serialized)
  warn "Warning: Protobuf detected an import path issue while loading generated file #{__FILE__}"
  imports = [
  ]
  imports.each do |type_name, expected_filename|
    import_file = pool.lookup(type_name).file_descriptor
    if import_file.name != expected_filename
      warn "- #{file.name} imports #{expected_filename}, but that import was loaded as #{import_file.name}"
    end
  end
  warn "Each proto file must use a consistent fully-qualified name."
  warn "This will become an error in the next major version."
end

module Payment
  CheckoutRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("payment.CheckoutRequest").msgclass
  CheckoutResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("payment.CheckoutResponse").msgclass
  WebhookRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("payment.WebhookRequest").msgclass
  WebhookResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("payment.WebhookResponse").msgclass
end
