# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: payment.proto for package 'Payment'

require 'grpc'
require 'payment_pb'

module Payment
  module StripeService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'payment.StripeService'

      rpc :Checkout, ::Payment::CheckoutRequest, ::Payment::CheckoutResponse
      rpc :Webhook, ::Payment::WebhookRequest, ::Payment::WebhookResponse
    end

    Stub = Service.rpc_stub_class
  end
end
