# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notes.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bnotes.proto\"h\n\x05Notes\x12\x0e\n\x06userId\x18\x01 \x01(\t\x12\x0e\n\x06\x66ileId\x18\x02 \x01(\t\x12\x0c\n\x04\x66ile\x18\x03 \x01(\x0c\x12\x1f\n\x08metadata\x18\x04 \x01(\x0b\x32\r.FileMetadata\x12\x10\n\x08\x66iletype\x18\x05 \x01(\t\"R\n\x0c\x46ileMetadata\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tpagecount\x18\x02 \x01(\x03\x12\x10\n\x08\x66ilesize\x18\x03 \x01(\x03\x12\x0e\n\x06locale\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTES']._serialized_start=15
  _globals['_NOTES']._serialized_end=119
  _globals['_FILEMETADATA']._serialized_start=121
  _globals['_FILEMETADATA']._serialized_end=203
# @@protoc_insertion_point(module_scope)
