# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import notes_pb2 as notes__pb2


class NoteServiceStub(object):
    """Define a service with RPC methods
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadNote = channel.unary_unary(
                '/NoteService/UploadNote',
                request_serializer=notes__pb2.UploadNoteRequest.SerializeToString,
                response_deserializer=notes__pb2.UploadNoteResponse.FromString,
                )
        self.RetrieveNote = channel.unary_unary(
                '/NoteService/RetrieveNote',
                request_serializer=notes__pb2.RetrieveNoteRequest.SerializeToString,
                response_deserializer=notes__pb2.RetrieveNoteResponse.FromString,
                )


class NoteServiceServicer(object):
    """Define a service with RPC methods
    """

    def UploadNote(self, request, context):
        """Define an RPC method to upload a note
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveNote(self, request, context):
        """Define an RPC method to retrieve a note
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NoteServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadNote': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadNote,
                    request_deserializer=notes__pb2.UploadNoteRequest.FromString,
                    response_serializer=notes__pb2.UploadNoteResponse.SerializeToString,
            ),
            'RetrieveNote': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveNote,
                    request_deserializer=notes__pb2.RetrieveNoteRequest.FromString,
                    response_serializer=notes__pb2.RetrieveNoteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NoteService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NoteService(object):
    """Define a service with RPC methods
    """

    @staticmethod
    def UploadNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NoteService/UploadNote',
            notes__pb2.UploadNoteRequest.SerializeToString,
            notes__pb2.UploadNoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrieveNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/NoteService/RetrieveNote',
            notes__pb2.RetrieveNoteRequest.SerializeToString,
            notes__pb2.RetrieveNoteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
