apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-storage
  namespace: eduhelper
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-storage
  template:
    metadata:
      labels:
        app: user-storage
    spec:
      containers:
      - name: user-storage
        image: 397789365835.dkr.ecr.ap-southeast-1.amazonaws.com/esd-eduhelper-eks-ecr-production:user-storage
        imagePullPolicy: Always
        ports:
        - containerPort: 50051
        env:
          - name: GRPC_PORT
            value: "0.0.0.0:50051"
          - name: DB
            valueFrom:
              secretKeyRef:
                key: DB_NAME
                name: eks-secrets
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                key: DB_HOST
                name: eks-secrets
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: DB_USERNAME
                name: eks-secrets
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DB_PASSWORD
                name: eks-secrets
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                key: CACHE_HOST
                name: eks-secrets
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_USERNAME
            valueFrom:
              secretKeyRef:
                key: CACHE_USERNAME
                name: eks-secrets
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: CACHE_PASSWORD
                name: eks-secrets
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: GOOGLE_CLIENT_ID
                name: eks-secrets
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: GOOGLE_CLIENT_SECRET
                name: eks-secrets
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: JWT_SECRET_KEY
                name: eks-secrets
          - name: SGID_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: SGID_CLIENT_ID
                name: eks-secrets
          - name: SGID_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: SGID_CLIENT_SECRET
                name: eks-secrets
          - name: SGID_REDIRECT_URL
            valueFrom:
              secretKeyRef:
                key: SGID_REDIRECT_URL
                name: eks-secrets
          - name: SGID_SCOPES
            valueFrom:
              secretKeyRef:
                key: SGID_SCOPES
                name: eks-secrets
          - name: SGID_PUBLIC_KEY
            valueFrom:
              secretKeyRef:
                key: SGID_PUBLIC_KEY
                name: eks-secrets
          - name: SGID_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                key: SGID_PRIVATE_KEY
                name: eks-secrets
          - name: URL_ENVIRONMENT_PREFIX
            value: "test"
          - name: MYINFO_CLIENT_ID
            value: "STG2-MYINFO-SELF-TEST"
          - name: MYINFO_SUBENTITY_ID
            value: ""
          - name: MYINFO_SCOPES
            value: "uinfin name email"
          - name: MYINFO_PURPOSE_ID
            value: "demonstration"
          - name: MYINFO_CALLBACK_URL
            value: "https://eduhelper.info/callback"
          - name: MYINFO_CLIENT_PRIVATE_SIGNING_KEY
            valueFrom:
              secretKeyRef:
                key: MYINFO_CLIENT_PRIVATE_SIGNING_KEY
                name: eks-secrets
          - name: MYINFO_CLIENT_PRIVATE_ENCRYPTION_KEYS
            valueFrom:
              secretKeyRef:
                key: MYINFO_CLIENT_PRIVATE_ENCRYPTION_KEYS
                name: eks-secrets
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always
status: {}