apiVersion: v1
kind: Service
metadata:
  name: kong-gateway
  namespace: eduhelper
spec:
  selector:
    app: kong-gateway
  ports:
    - name: http
      port: 8000
      targetPort: 8000
    - name: https
      port: 8443
      targetPort: 8443
    - name: admin
      port: 8444
      targetPort: 8444
  
