# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: stripe_webhook.proto for package ''

require 'grpc'
require 'stripe_webhook_pb'

module StripeWebhook
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'StripeWebhook'

    rpc :SendEvent, ::StripeEvent, ::StripeEvent
    rpc :CreateCheckoutSession, ::Empty, ::CheckoutSession
  end

  Stub = Service.rpc_stub_class
end
