apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth
  namespace: itsag2t2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-auth
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
      - name: user-auth
        image: 163683790602.dkr.ecr.ap-southeast-1.amazonaws.com/itsag2t2-eks-ecr-production:user-auth
        imagePullPolicy: Always
        ports:
        - containerPort: 50052
        env:
          - name: GRPC_USER_AUTH_SERVICE_ADDRESS
            value: "0.0.0.0:50052"
          - name: JWT_SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: JWT_SECRET_KEY
                name: eks-secrets
          - name: SOURCE_EMAIL
            valueFrom:
              secretKeyRef:
                key: SOURCE_EMAIL
                name: eks-secrets
          - name: DB
            valueFrom:
              secretKeyRef:
                key: DB
                name: eks-secrets
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                key: DB_USER
                name: eks-secrets
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                key: DB_PASSWORD
                name: eks-secrets
          - name: DB_WRITE_HOST
            valueFrom:
              secretKeyRef:
                key: DB_WRITE_HOST
                name: eks-secrets
          - name: DB_READ_HOST
            valueFrom:
              secretKeyRef:
                key: DB_READ_HOST
                name: eks-secrets
          - name: DB_PORT
            value: "5432"
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                key: REDIS_HOST
                name: eks-secrets
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_USERNAME
            value: default
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                key: REDIS_PASSWORD
                name: eks-secrets
          - name: REDIS_CLUSTER_MODE
            value: cluster
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: GOOGLE_CLIENT_ID
                name: eks-secrets
          - name: GOOGLE_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                key: GOOGLE_CLIENT_SECRET
                name: eks-secrets
          - name: AWS_REGION
            value: ap-southeast-1
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50052"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50052"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
      restartPolicy: Always
status: {}